[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gm-proj"
version = "0.1.0"
description = "gm_proj project"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools]
packages = ["src"]
